### ISSUE TITLE
Create an Endpoint to Query Following

### ISSUE THREAD

**Issue by William-McGonagle** [fairfield-programming/backend-server#47]
## Idea
_Full Idea Here - #45_

Users need to see what accounts they are following. To do this, there needs to be a single endpoint that can just list all of the accounts that a user is following along with the profile picture, name, and account id. This will help our frontend team a lot because only the important stuff will be loaded. 

The endpoint will be at `/user/:id/following`.

## Todo
- [x] Endpoint
     - [x] `GET /user/:id/following`
- [x] Testing
     - [x] `GET /user/:id/following`

**Comment by MassiGy** [comment]
Hey there,

I will be interested to work on this on.

Massiles.

**Comment by MassiGy** [comment]
Hey @William-McGonagle,

I'am currently implementing this system. I want to note that the appropriate route signature will be `/user/followings` since we have `/user/followers` on the code base. 

What I mean is that we do not want to add the `/:id/` since we will allow the user to only see whom is currently following. Because, it does not make sense to see who other are following. ( +Privacy )

Hope that is clear.
Massiles.
