### ISSUE TITLE
Focus on the test suite

### ISSUE THREAD

**Issue by NikitaLejnev** [fairfield-programming/backend-server#89]
## Idea
The test suite is especially affected by code duplication most tests are identical except for a value of one variable. Creating reusable test functions will help us write tests quicker and focus on growing the project.

## Todo
- Consider using some coverage analysis tool.
- Create more tests.
- Review the quality of the test suite.

**Comment by William-McGonagle** [comment]
I think test suites are always going to have a ton of code duplication- it's a known issue in the jest library because their focus is to make it human-readable. But, I can try to get around this by seeing if we can get our code linter to ignore the testing suite. 

Also, I would agree that we need more tests.
